# Generated by Django 3.0.5 on 2020-08-13 10:50

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_tag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tags_norm',
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
