# Generated by Django 3.0.5 on 2020-08-11 06:16

from django.db import migrations, models
import djongo.models.fields
import image_tag_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=256)),
                ('post_time', models.CharField(max_length=256)),
                ('push', models.CharField(max_length=8)),
                ('imgs', djongo.models.fields.JSONField()),
                ('author', models.CharField(max_length=256)),
                ('comments', djongo.models.fields.ArrayField(model_container=image_tag_app.models.Comments)),
                ('tags', djongo.models.fields.JSONField()),
                ('taggers', djongo.models.fields.JSONField()),
            ],
        ),
    ]
