# Generated by Django 3.0.5 on 2020-08-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_tag_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
