# Generated by Django 3.0.5 on 2020-08-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_tag_app', '0002_data_tags_norm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='tags_norm',
            new_name='tags_average',
        ),
    ]
